"""Final BD

Revision ID: 20cb7767ab14
Revises: fd812dbd75ee
Create Date: 2025-05-13 20:35:31.326286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cb7767ab14'
down_revision: Union[str, None] = 'fd812dbd75ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.add_column('results', sa.Column('game_id', sa.UUID(), nullable=False))
    op.drop_constraint('results_user_id_fkey', 'results', type_='foreignkey')
    op.drop_constraint('results_challenge_id_fkey', 'results', type_='foreignkey')
    op.create_foreign_key(None, 'results', 'games', ['game_id'], ['id'])
    op.drop_column('results', 'user_id')
    op.drop_column('results', 'challenge_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('challenge_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('results', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_foreign_key('results_challenge_id_fkey', 'results', 'challenges', ['challenge_id'], ['id'])
    op.create_foreign_key('results_user_id_fkey', 'results', 'users', ['user_id'], ['id'])
    op.drop_column('results', 'game_id')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
