"""DB V2

Revision ID: f0f7c7670844
Revises: dc8b61d3af84
Create Date: 2025-05-09 21:49:48.871622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f7c7670844'
down_revision: Union[str, None] = 'dc8b61d3af84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_details_id'), 'details', ['id'], unique=False)
    op.create_index(op.f('ix_details_name'), 'details', ['name'], unique=False)
    op.drop_index('ix_rankings_id', table_name='rankings')
    op.drop_table('rankings')
    op.add_column('results', sa.Column('detail_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'results', 'details', ['detail_id'], ['id'])
    op.drop_column('results', 'details')
    op.add_column('users', sa.Column('total_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_score')
    op.add_column('results', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'detail_id')
    op.create_table('rankings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rankings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rankings_pkey'),
    sa.UniqueConstraint('user_id', name='rankings_user_id_key')
    )
    op.create_index('ix_rankings_id', 'rankings', ['id'], unique=False)
    op.drop_index(op.f('ix_details_name'), table_name='details')
    op.drop_index(op.f('ix_details_id'), table_name='details')
    op.drop_table('details')
    # ### end Alembic commands ###
