"""Modify Models

Revision ID: fd812dbd75ee
Revises: f0f7c7670844
Create Date: 2025-05-13 20:17:18.130478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd812dbd75ee'
down_revision: Union[str, None] = 'f0f7c7670844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('results_detail_id_fkey', 'results', type_='foreignkey')
    op.drop_column('results', 'detail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('detail_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('results_detail_id_fkey', 'results', 'details', ['detail_id'], ['id'])
    # ### end Alembic commands ###
